{
 "title": "Fail2ban Monitoring",
 "description": "Monitoring for Fail2Ban",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Les attaques selon les villes",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n time AS \"time\",\n  lat,\n  lng,\n  city,\n  count(city) as \"ciudades\",\n  ip as \"metric\"\nFROM grafana.data\nWHERE\n  $__timeFilter(time)\ngroup by city"
    },
    {
     "rawSql": "SELECT\n time AS \"time\",\n  city,\n  count(city) as \"metrica\"\n  \nFROM grafana.data \ngroup by city"
    }
   ]
  },
  {
   "title": "Les attaques selon les pays",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 11, "x": 10, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n time AS \"time\",\n  avg(lat) as \"lat\",\n  avg(lng) as \"lng\",\n  country,\n  count(country) as \"paises\",\n  ip as \"metric\"\nFROM grafana.data\nWHERE\n  $__timeFilter(time)\ngroup by country"
    }
   ]
  },
  {
   "title": "Nombre d'IP bannies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \ncount(country),time\nfrom grafana.data\n"
    }
   ]
  },
  {
   "title": "Les attaques selon le lieu",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 13 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n time AS \"time\",\n  lat,\n  lng,\n  city\nFROM grafana.data\nWHERE\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Les fournisseurs d'accès",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 11, "x": 10, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n  isp,\n  country,\n  count(isp) as \"isp_count\"\nFROM grafana.data\ngroup by country,isp\norder by isp_count desc"
    }
   ]
  }
 ]
}